name: Demo Action 
run-name: ${{github.actor}} Run Demo Action
on: 
- pull_request

jobs:
  Check-Demo-Action:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Event Name = ${{ github.event_name }}."

      - name: Print Branch Name
        run: echo "Branch Name = ${{ steps.branch-name.outputs.current_branch }}"
      
      - name: Running on the default branch
        if: steps.branch-name.outputs.is_default == 'true'
        run: |
          echo "Running on default: ${{ steps.branch-name.outputs.current_branch }}" 
        
