name: Demo Action 
run-name: ${{github.actor}} Run Demo Action
on: 
- pull_request

jobs:
  Check-Demo-Action:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Event Name = ${{ github.event_name }}."
 
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Print Branch Name
        run: echo "Branch Name = ${{ steps.extract_branch.outputs.branch }}"

        
        
