name: Android CI

on:
  push:
    branches: [ "new-action-1" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: assembleDebug
      run: ./gradlew assembleDebug
    - run: |
          files=$(ls $BUILD_PATH)
          IFS=$'\n' files_array=($files)
          first_file=${files_array[0]}
          echo $first_file
          echo "::set-output name=file_name::${first_file}"
