name: Demo Action 
run-name: ${{github.actor}} Run Demo Action
on: 
- pull_request

jobs:
  Check-Demo-Action:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: echo "State = ${{ github.event.review.state }}"
        
      - name: Check if Approved
        run: |
          if [[${{ github.event.review.state }} == 'approved']]; then
            echo "No issue"
          else
            echo "Pr SHould Be approved"
            exit 1

      - run: echo "Event Name = ${{ github.event_name }}."

      - name: Print Branch Name
        run: echo "Branch Name = ${{ github.head_ref }}"
