name: Check Branch Pattern
run-name: Check Branch Pattern [${{ github.actor }}]

on:
  pull_request:
    types: [ synchronize, labeled, edited ]
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  branch-pattern:
    name: Check Branch Pattern
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: write
      pull-requests: write

    steps:
      - name: Base branch as release branch
        run: |
          if [[ "${{ github.base_ref }}" =~ release/[0-9]+.[0-9]+/[0-9]+.[0-9]+.[0-9]+ ]]; then
            if [[ "${{ github.head_ref }}" =~ feature/[A-Za-z]+-[0-9]+/master || "${{ github.head_ref }}" =~ bugfix/[A-Za-z]+-[0-9]+/master ]]; then
              echo "No issue"
            else
              echo "Branch name should be like: feature/MOB-111/master/short_desc or bugfix/MOB-111/master/short_desc"
              exit 1
            fi
          fi

      - name: Base branch as master branch
        run: |
          if [[ "${{ github.base_ref }}" =~ master || "${{ github.base_ref }}" =~ main ]]; then
            if [[ "${{ github.head_ref }}" =~ release/[0-9]+.[0-9]+/[0-9]+.[0-9]+.[0-9]+ ]]; then
              echo "No issue"
            else
              echo "Release branch name should be like: release/1.1/1.1.0"
              exit 1
            fi
          fi
