name: Demo Action 
run-name: ${{github.actor}} Run Demo Action
on: 
- pull_request

jobs:
  Check-Demo-Action:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Event Name = ${{ github.event_name }}."
 
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Print Branch Name
        run: echo "Branch Name = ${{ steps.extract_branch.outputs.branch }}"

      - name: Check Base & Current Branch Pattern
        run: |
          if [[ "${{ github.base_ref }}" =~ release/[0-9]+.[0-9]+/[0-9]+.[0-9]+.[0-9]+ ]]; then
            if [[ "${{ github.head_ref }}" =~ feature/[A-Za-z]+-[0-9]+/master || "${{ github.head_ref }}" =~ bugfix/[A-Za-z]+-[0-9]+/master ]]; then
              echo "No issue"
            else
              echo "Branch name should be like: feature/MOB-111/master/short_desc or bugfix/MOB-111/master/short_desc"
              exit 1
            fi
          fi

        
        
