name: Demo Action 
run-name: ${{github.actor}} Run Demo Action
on: 
- pull_request

jobs:
  Check-Demo-Action:
    runs-on: ubuntu-latest
    steps:          
      - name: Check if Approved
        run: |
          if [[${{ github.base_ref }} =~ 'approved']]; then
            echo "No issue"
          else
            echo "Pr SHould Be approved"
          exit 1

      - run: echo "Event Name = ${{ github.event_name }}."

      - name: Print Branch Name
        run: echo "Branch Name = ${{ github.head_ref }}"

        
        github.event.review.state == 'approved'
