name: Demo Action 
run-name: ${{github.actor}} Run Demo Action
on: 
- pull_request

jobs:
  Check-Demo-Action:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Event Name = ${{ github.event_name }}."
